### ISSUE TITLE
Allow usage of System.Text.Json versions greater than 7.0.0

### ISSUE THREAD

**Issue by Floopy-Doo** [Particular/NServiceBus.ServicePlatform.Connector#150]
### Symptoms

Unable to update to System.Text.Json 7.0.0 or later versions.

### Who's affected

Anyone who wants to update to System.Text.Json 7.0.0 or later.

### Root cause

A Microsoft dependency was defined as a NuGet version range instead of as a regular version number.

## Original User report

I am trying to use the ServicePlatform.Connector package in our software, but due to the dependency constraints of System.Text.Json i need to use version > 7.0.0. I would rather us this packages instead of each individual sub-package (Metrics, Heartbeats, etc.) by itself.

The packages constraints for ServicePlatform.Connector forces the usage of versions 6.0.5 <= x < 7.0.0 of System.Text.Json.

I would propose to use the same constraint as NServiceBus for System.Text.Json to be in line with the core packages.

Kind regards
Florian

**Comment by DavidBoike** [comment]
Now released: https://discuss.particular.net/t/nservicebus-serviceplatform-connector-2-0-1-patch-release-available/3384
